[build]
  functions = "netlify/functions"
  publish = "."
[[redirects]]
  from = "/goa-real-estate-regulation-and-development-registration-of-real-estate-projects-registration-of-real-estate-agents-rates-of-interest-and-disclosures-on-website-rules.pdf"
  to = "/static/goa-real-estate-regulation-and-development-registration-of-real-estate-projects-registration-of-real-estate-agents-rates-of-interest-and-disclosures-on-website-rules.pdf"
  status = 200
